# Generated by Django 4.2.11 on 2024-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice_count',
            field=models.IntegerField(default=0),
        ),
    ]
