# Generated by Django 4.2.11 on 2024-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_customuser_user_customuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_practice_count',
            field=models.IntegerField(default=0),
        ),
    ]
